name: k8s
description: Runs your build step as a kubernetes job
author: https://github.com/dln
requirements:
- jq
- jsonnet
- kubectl
configuration:
  properties:
    image:
      type: string
    always-pull:
      type: boolean
    command:
      type: array
    entrypoint:
      type: array
    environment:
      type: array
    init-image:
      type: string
    privileged:
      type: boolean
    secret-name:
      type: string
    ssh-secret-key:
      type: string
    agent-token-secret-key:
      type: string
    build-path-host-path:
      type: string
    build-path-pvc:
      type: string
    workdir:
      type: string
  required:
  - image
  additionalProperties: false
