foo:
  bar: foobar
  baz: some other stuff
steps:
  - name: ":buildkite: test"
    agents:
      queue: 'dlntest-k8s'
    plugins:
      EmbarkStudios/k8s:
        image: alpine
        entrypoint: ["sh"]
        command: ["-c", "df -h"]
        git-credentials-secret-key: git-credentials
        git-ssh-secret-key: git-ssh-key
        environment:
          - FOO=bar
          - BAZ=tjosan hejsan
