steps:
  - agents:
      queue: dlntest-k8s
    commands:
      - uname -a
      - echo 'Hello, World!'
      - ls -lR /foo
    plugins:
      - EmbarkStudios/k8s:
          image: alpine
          mount-secret:
            - dlntest:/foo/bar
            - dlntest2:/foo/baz
