foo:
  bar: foobar
  baz: some other stuff
steps:
  - commands:
      - uname -a
      - echo 'Hello, World!'
      - env
    agents:
      queue: 'dlntest-k8s'
    plugins:
      - EmbarkStudios/k8s:
          image: alpine
          git-credentials-secret-key: git-credentials
          git-ssh-secret-key: git-ssh-key
