foo:
  bar: foobar
  baz: some other stuff
steps:
  - name: ":buildkite: test"
    agents:
      queue: 'dlntest-k8s'
    plugins:
      EmbarkStudios/k8s:
        image: alpine
        entrypoint: ["ls"]
        command: ["-1", "/"]
        environment:
          - FOO=bar
          - BAZ=tjosan hejsan
