foo:
  bar: foobar
  baz: some other stuff
steps:
  - agents:
      queue: 'dlntest-k8s'
    plugins:
      - EmbarkStudios/k8s:
          image: embarkstudios/fortune
          command: ["startrek"]
          git-credentials-secret-key: git-credentials
          git-ssh-secret-key: git-ssh-key
