foo:
  bar: foobar
  baz: some other stuff
steps:
  - name: ":buildkite: test"
    agents:
      queue: 'dlntest-k8s'
    plugins:
      EmbarkStudios/k8s:
        image: alpine
        entrypoint: ["sh"]
        command: ["-c", "uname -a; env; ls;"]
        environment:
          - FOO=bar
          - BAZ=tjosan hejsan
