steps:
  - name: Build and publish k8s-buildkite-agent container image
    agents:
      queue: k8s
    plugins:
      - EmbarkStudios/k8s#0.9.2:
          image: gcr.io/kaniko-project/executor:debug
          command:
            - --context=dir://$PWD
            - --destination=embarkstudios/k8s-buildkite-agent
          mount-secret:
            - docker-hub-credentials:/kaniko/.docker
