steps:
  - name: shellcheck hooks
    agents:
      queue: default
      os: linux
    command:
      - echo "Running shellcheck"
      - shellcheck hooks/*
    plugins:
      - EmbarkStudios/k8s#1.0.1:
          image: koalaman/shellcheck-alpine
  - wait
  - name: Build and publish k8s-buildkite-agent container image
    agents:
      queue: default
      os: linux
    plugins:
      - EmbarkStudios/k8s#1.0.1:
          image: gcr.io/kaniko-project/executor:latest
          command:
            - --destination=embarkstudios/k8s-buildkite-agent
            - --context=dir://$PWD
            - --reproducible
            - --cache=true
            - --cache-repo=kaniko-cache.buildkite.svc.cluster.local/kaniko/cache
            - --cache-dir=$BUILDKITE_BUILD_PATH/_kaniko_cache
          mount-secret:
            - docker-hub-credentials:/kaniko/.docker
