steps:
  - agents:
      queue: dlntest-k8s
    commands:
      - uname -a
      - echo 'Hello, World!'
      - ls -lR /foo
      - cat /foo/bar/foo
      - cat /foo/bar/bar
    plugins:
      - EmbarkStudios/k8s:
          image: alpine
          mount-secret: dlntest:/foo/bar
